export const ROLE_LIST_REQUEST = 'ROLE_LIST_REQUEST';
export const ROLE_LIST_SUCCESS = 'ROLE_LIST_SUCCESS';
export const ROLE_LIST_FAIL = 'ROLE_LIST_FAIL';
export const ROLE_LIST_RESET = 'ROLE_LIST_RESET';

export const DEPARTMENT_LIST_REQUEST = 'DEPARTMENT_LIST_REQUEST';
export const DEPARTMENT_LIST_SUCCESS = 'DEPARTMENT_LIST_SUCCESS';
export const DEPARTMENT_LIST_FAIL = 'DEPARTMENT_LIST_FAIL';
export const DEPARTMENT_LIST_RESET = 'DEPARTMENT_LIST_RESET';

export const DEPARTMENT_ADD_REQUEST = 'DEPARTMENT_ADD_REQUEST';
export const DEPARTMENT_ADD_SUCCESS = 'DEPARTMENT_ADD_SUCCESS';
export const DEPARTMENT_ADD_FAIL = 'DEPARTMENT_ADD_FAIL';

export const ROLE_ADD_REQUEST = 'ROLE_ADD_REQUEST';
export const ROLE_ADD_SUCCESS = 'ROLE_ADD_SUCCESS';
export const ROLE_ADD_FAIL = 'ROLE_ADD_FAIL';

export const DEPARTMENT_DELETE_REQUEST = 'DEPARTMENT_DELETE_REQUEST';
export const DEPARTMENT_DELETE_SUCCESS = 'DEPARTMENT_DELETE_SUCCESS';
export const DEPARTMENT_DELETE_FAIL = 'DEPARTMENT_DELETE_FAIL';

export const ROLE_DELETE_REQUEST = 'ROLE_DELETE_REQUEST';
export const ROLE_DELETE_SUCCESS = 'ROLE_DELETE_SUCCESS';
export const ROLE_DELETE_FAIL = 'ROLE_DELETE_FAIL';

export const ROLE_DETAILS_SUCCESS = 'ROLE_DETAILS_SUCCESS';
export const ROLE_DETAILS_FAIL = 'ROLE_DETAILS_FAIL';
export const ROLE_DETAILS_REQUEST = 'ROLE_DETAILS_REQUEST';
export const ROLE_DETAILS_RESET = 'ROLE_DETAILS_RESET';

export const DEPARTMENT_DETAILS_SUCCESS = 'DEPARTMENT_DETAILS_SUCCESS';
export const DEPARTMENT_DETAILS_FAIL = 'DEPARTMENT_DETAILS_FAIL';
export const DEPARTMENT_DETAILS_REQUEST = 'ROLE_DETAILS_REQUEST';
export const DEPARTMENT_DETAILS_RESET = 'DEPARTMENT_DETAILS_RESET';

export const DEPARTMENT_UPDATE_REQUEST = 'DEPARTMENT_UPDATE_REQUEST';
export const DEPARTMENT_UPDATE_SUCCESS = 'DEPARTMENT_UPDATE_SUCCESS';
export const DEPARTMENT_UPDATE_FAIL = 'DEPARTMENT_UPDATE_FAIL';
export const DEPARTMENT_UPDATE_RESET = 'DEPARTMENT_UPDATE_RESET';

export const ROLE_UPDATE_REQUEST = 'ROLE_UPDATE_REQUEST';
export const ROLE_UPDATE_SUCCESS = 'ROLE_UPDATE_SUCCESS';
export const ROLE_UPDATE_FAIL = 'ROLE_UPDATE_FAIL';
export const ROLE_UPDATE_RESET = 'ROLE_UPDATE_RESET';

export const STANDARD_UPDATE_REQUEST = 'STANDARD_UPDATE_REQUEST';
export const STANDARD_UPDATE_SUCCESS = 'STANDARD_UPDATE_SUCCESS';
export const STANDARD_UPDATE_FAIL = 'STANDARD_UPDATE_FAIL';
export const STANDARD_UPDATE_RESET = 'STANDARD_UPDATE_RESET';

export const STANDARD_LIST_REQUEST = 'STANDARD_LIST_REQUEST';
export const STANDARD_LIST_SUCCESS = 'STANDARD_LIST_SUCCESS';
export const STANDARD_LIST_FAIL = 'STANDARD_LIST_FAIL';
export const STANDARD_LIST_RESET = 'STANDARD_LIST_RESET';

export const STANDARD_ADD_REQUEST = 'STANDARD_ADD_REQUEST';
export const STANDARD_ADD_SUCCESS = 'STANDARD_ADD_SUCCESS';
export const STANDARD_ADD_FAIL = 'STANDARD_ADD_FAIL';

export const STANDARD_DELETE_REQUEST = 'STANDARD_DELETE_REQUEST';
export const STANDARD_DELETE_SUCCESS = 'STANDARD_DELETE_SUCCESS';
export const STANDARD_DELETE_FAIL = 'STANDARD_DELETE_FAIL';

export const STANDARD_DETAILS_SUCCESS = 'STANDARD_DETAILS_SUCCESS';
export const STANDARD_DETAILS_FAIL = 'STANDARD_DETAILS_FAIL';
export const STANDARD_DETAILS_REQUEST = 'STANDARD_DETAILS_REQUEST';
export const STANDARD_DETAILS_RESET = 'STANDARD_DETAILS_RESET';
