export const PROJECT_ADD_REQUEST = 'PROJECT_ADD_REQUEST';
export const PROJECT_ADD_SUCCESS = 'PROJECT_ADD_SUCCESS';
export const PROJECT_ADD_FAIL = 'PROJECT_ADD_FAIL';

export const PROJECT_DELETE_REQUEST = 'PROJECT_DELETE_REQUEST';
export const PROJECT_DELETE_SUCCESS = 'PROJECT_DELETE_SUCCESS';
export const PROJECT_DELETE_FAIL = 'PROJECT_DELETE_FAIL';

export const PROJECT_LIST_REQUEST = 'PROJECT_LIST_REQUEST';
export const PROJECT_LIST_SUCCESS = 'PROJECT_LIST_SUCCESS';
export const PROJECT_LIST_FAIL = 'PROJECT_LIST_FAIL';
export const PROJECT_LIST_RESET = 'PROJECT_LIST_RESET';

export const PROJECT_UPDATE_REQUEST = 'PROJECT_UPDATE_REQUEST';
export const PROJECT_UPDATE_SUCCESS = 'QUESTION_UPDATE_SUCCESS';
export const PROJECT_UPDATE_FAIL = 'PROJECT_UPDATE_FAIL';
export const PROJECT_UPDATE_RESET = 'PROJECT_UPDATE_RESET';

export const PROJECT_DETAILS_REQUEST = 'PROJECT_DETAILS_REQUEST';
export const PROJECT_DETAILS_SUCCESS = 'PROJECT_DETAILS_SUCCESS';
export const PROJECT_DETAILS_FAIL = 'PROJECT_DETAILS_FAIL';
export const PROJECT_DETAILS_RESET = 'PROJECT_DETAILS_RESET';

/*
There is Problem from EditProjectQuestionScreen & UsersSingleProjectScreen
The PRoblem is to Maintain A state. So i am Solving the problem by duplication of state
basically 'getProjectcDetails' action and 'getProjectDetails' action are same
pleace check the both actions are requestiong the same URL of backend
*/
export const PROJECT_DETAIL_QUESTION_REQUEST = 'PROJECT_DETAIL_QUESTION_REQUEST';
export const PROJECT_DETAIL_QUESTION_SUCCESS = 'PROJECT_DETAIL_QUESTION_SUCCESS';
export const PROJECT_DETAIL_QUESTION_FAIL = 'PROJECT_DETAIL_QUESTION_FAIL';
export const PROJECT_DETAIL_QUESTION_RESET = 'PROJECT_DETAIL_QUESTION_RESET';

export const PROJECT_MY_LIST_REQUEST = 'PROJECT_MY_LIST_REQUEST';
export const PROJECT_MY_LIST_SUCCESS = 'PROJECT_MY_LIST_SUCCESS';
export const PROJECT_MY_LIST_FAIL = 'PROJECT_MY_LIST_FAIL';
export const PROJECT_MY_LIST_RESET = 'PROJECT_MY_LIST_RESET';

export const PROJECT_UPDATE_QUESTION_REQUEST = 'PROJECT_UPDATE_QUESTION_REQUEST';
export const PROJECT_UPDATE_QUESTION_SUCCESS = 'PROJECT_UPDATE_QUESTION_SUCCESS';
export const PROJECT_UPDATE_QUESTION_FAIL = 'PROJECT_UPDATE_QUESTION_FAIL';
export const PROJECT_UPDATE_QUESTION_RESET = 'PROJECT_UPDATE_QUESTION_RESET';

export const PROJECT_ADD_VERSION2_REQUEST = 'PROJECT_ADD_VERSION2_REQUEST';
export const PROJECT_ADD_VERSION2_SUCCESS = 'PROJECT_ADD_VERSION2_SUCCESS';
export const PROJECT_ADD_VERSION2_FAIL = 'PROJECT_ADD_VERSION2_FAIL';
export const PROJECT_ADD_VERSION2_RESET = 'PROJECT_ADD_VERSION2_RESET';

export const PROJECT_ADD_VERSION3_REQUEST = 'PROJECT_ADD_VERSION3_REQUEST';
export const PROJECT_ADD_VERSION3_SUCCESS = 'PROJECT_ADD_VERSION3_SUCCESS';
export const PROJECT_ADD_VERSION3_FAIL = 'PROJECT_ADD_VERSION3_FAIL';
export const PROJECT_ADD_VERSION3_RESET = 'PROJECT_ADD_VERSION3_RESET';
